package net.monkeystudio.chatrbtw.mapper;


import net.monkeystudio.chatrbtw.entity.GlobalConfig;

import java.util.List;


/**
 * 全局配置表接口
 * @author hebo2
 *
 */
public interface GlobalConfigMapper 
{
	
	/**
	 * 查询所有记录
	 * @return
	 */
	public List<GlobalConfig> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cons_global_config
     */
    int deleteByPrimaryKey(String key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cons_global_config
     */
    int insert(GlobalConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cons_global_config
     */
    int insertSelective(GlobalConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cons_global_config
     */
    GlobalConfig selectByPrimaryKey(String key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cons_global_config
     */
    int updateByPrimaryKeySelective(GlobalConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cons_global_config
     */
    int updateByPrimaryKey(GlobalConfig record);
    
    /**
     * 用于测试数据库连接，结果返回1
     * insert into g_global_config (`KEY`,`VALUE`,`DESC`) values ('Z_FOR_TEST','testconnect','用于测试数据库连接');
     * @return
     */
    public String selectTest();
    
}
